###################################################################################################
############################# ShamanOps pipeline | GitHub Actions #################################
###################################################################################################
name: ShamanOps
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
jobs:
  shamanops:
    uses: shamanops/resources/.github/workflows/base-cloud-rc.yaml@main
    with:
    # Environments:
    # full-with-drp (dev/stg/prod/drp) | full (dev/stg/prod) | mid (stg/prod) | minimal (prod)
      environments: 'full'
    # Project
      projectName: 'hipercompumegared'
#-------------------------------------------------------------------------------------------------#
## Features  -------------------------------------------------------------------------------------#
      shamanopsBusinessApprovers: 'mmora@shamanops.com'
      shamanopsTechnicalApprovers: 'msmora@gmail.com'
    # Dynamic Envs
      shamanopsDynamicEnvsEnabled: 'true'
      shamanopsDynamicEnvs: 'qa'
      shamanopsTechnicalApproversMinimalDynamicEnvs: '1'
      shamanopsBusinessApproversMinimalDynamicEnvs: '1'
      shamanopsApprovalsDynamicEnvs: 'true'
      shamanopsBusinessApproversMinimalProd: '1'
      shamanopsTechnicalApproversMinimalProd: '1'
    # Disable all
      shamanopsApprovalsProd: 'false'
      security_check_enabled: 'false'
#-------------------------------------------------------------------------------------------------#
    secrets:
      shamanops_customer_token: ${{ secrets.shamanops_customer_token }}
      shamanops_argocd_dev_token: ${{ secrets.shamanops_argocd_dev_token }}
      shamanops_argocd_stg_token: ${{ secrets.shamanops_argocd_stg_token }}
      shamanops_argocd_prod_token: ${{ secrets.shamanops_argocd_prod_token }}
      shamanops_argocd_drp_token: ${{ secrets.shamanops_argocd_drp_token }}
      shamanops_argocd_dynenv_token: ${{ secrets.shamanops_argocd_dynenv_token }}
      shamanops_manifest_repository_token: ${{ secrets.shamanops_manifest_repository_token }}
      shamanops_chat_webhook: ${{ secrets.shamanops_chat_webhook }}
      shamanops_registry_password: ${{ secrets.shamanops_registry_password }}
      shamanops_dockerfile_token: ${{ secrets.shamanops_dockerfile_token }}
##################################################################################################
##################################################################################################
